# Generated by Django 6.0.4 on 2026-05-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="is_leader",
            field=models.BooleanField(default=False, verbose_name="팀장"),
        ),
    ]
