# Generated by Django 6.0.4 on 2026-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_is_leader_to_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="resubmit_count",
            field=models.PositiveIntegerField(default=0, verbose_name="재제출 횟수"),
        ),
    ]
