# Generated by Django 6.0.4 on 2026-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_resubmit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='ai_job_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='AI 검증 job ID'),
        ),
    ]
