# Generated by Django 6.0.4 on 2026-05-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectfile_ai_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='ai_final_grade',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='AI 종합 판정'),
        ),
    ]
