# Generated by Django 6.0.4 on 2026-05-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_filereviewitem_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='ai_summary',
            field=models.TextField(blank=True, default='', verbose_name='AI 종합 요약'),
        ),
    ]
