# Generated by Django 6.0.4 on 2026-06-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filereviewitem',
            name='judgment',
            field=models.CharField(default='FAIL', max_length=40, verbose_name='판정'),
        ),
    ]
